### ISSUE TITLE
not connect to openfire server

### ISSUE THREAD

**Issue by RaulGaLo** [pazznetwork/ngx-chat#2]
I can not connect to openfire server, any special configuration for this server?

**Comment by lordoliver** [comment]
Did you allow BOSH clients?

**Comment by trampi** [comment]
Hello @RaulGaLo,

with the following settings, a connection can be established:
![settings](https://user-images.githubusercontent.com/4292951/49153693-bb2e3d80-f316-11e8-9f5a-8d4d6ff44e4a.PNG)

Use wss and port 7443. Use the domain names instead of the IP so that the TLS-Certificates work.

Do not hesitate if you have further questions :-)

**Comment by RaulGaLo** [comment]
Work!!!, thank you. (please delete my domain)

**Comment by RaulGaLo** [comment]
> Work!!!, thank you. (please delete my domain)
