### ISSUE TITLE
Groupchats appear in Contacts, and cannot be deleted

### ISSUE THREAD

**Issue by DevRichter** [pazznetwork/ngx-chat#49]
Hello,

i have a Problem where after i send a Message to a Groupchat, it creates a new Contact with the JID of the room in my Contacts (for example testroom@conference.2345423ds). I cant find a call for the method addContact() or getOrCreateContactById(). Any Ideas how that might happen? 

Also now that i have these rooms as actual contacts, i want to remove them from my contacts. But i get the following error: 

`ChatService: unknown stanza <= <iq xmlns="jabber:client" type="error" id="692-226" from="test888@conference.mit.profi.de" to="alice@mit.profi.de/505al42tos"><query xmlns="jabber:iq:roster"><item jid="alice@mit.profi.de" subscription="remove"/></query><error code="400" type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">IQ request cannot be processed by the MUC room itself.</text></error></iq>`

This error persists for existing rooms, when trying to removeContact().

`ChatService: unknown stanza <= <presence xmlns="jabber:client" type="error" from="wahwah@conference.mit.profi.de" to="alice@mit.profi.de/505al42tos"><error code="400" type="modify"><jid-malformed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">A nickname (resource-part) is required in order to join a room.</text></error></presence>`

This error persists for deleted rooms, when trying to removeContact().

Using the deleteRoom() method yields the deletion of the room, but not of the removal of the groupchat within my contacts, any suggestions?

**Comment by trampi** [comment]
Hi @DevRichter,

groupchats appearing in contacts is definitely not intended and hint at message stanzas with a type not equal to groupchat.

Just to be sure, when you log out and log in, do you still get the conference as contact? I guess you do, right?

If thats the case, then I would guess the message has been sent as a type 'chat'-message instead of a type 'groupchat' message.

How do you send the message to the room? When using the `ChatMessageInputComponent` and the `room` attribute, then it should work correctly. If you're sending it manually, be sure to use `MultiUserChatPlugin` to send the message like this:

```
this.chatService.getPlugin(MultiUserChatPlugin).sendMessage(this.room, this.message);
```

Feel free to add code samples if it is convenient.

Should you confirm to use it correctly, I would try to reproduce it with OpenFire and Multi User Chats locally, might be non-standard-compliant behavior.

**Comment by DevRichter** [comment]
Hi @trampi,

i do get conferences as contacts, even after i log in and out. 

`sendMessage(contact, message) {
    this.ngxChatService.sendMessage(contact, message);
}`
`sendRoomMessage(room, message) {
    this.chatPlugin.sendMessage(room, message);
 }`

i do call the sending of messages differently. I made sure to check that it might call the wrong function, but it doesnt. It did work before as intended. I had a problem with loading the data asynchronously, in the end what worked was using callbacks to load the data for the group chats and single chats. 

After i implemented that, the problem started to appear, but even when i revert to normal asynchronous loading with Promises, the Problem still persists and i cant seem to find the root of the Problem. Any more suggestions? I might suspect that the method getOrCreateContactById() might be called internally somewhere, but even with the debugger i cant seem to find a call for that.

**Comment by trampi** [comment]
Hi @DevRichter,
I will try to reproduce it locally tomorrow morning.

When logging in, the message archive gets requested via message-archive.plugin.ts -> you might want to set a breakpoint there around line 136. There is a call to `getOrCreateContactById()` to append the received archived message to a contact. 
**In a Multi-User-Chat, this branch should never be taken, only for person-to-person chats.**

Another suspect might be the `MessageCarbonsPlugin` around line 54.

I would also recommend to take a look at the network tab of the dev tools, open the websocket connection to openfire and search for the content of one of the false groupchat messages. If you could post one of these message stanzas here it would probably shed some light on the root cause of this issue.

All the best,
trampi

**Comment by DevRichter** [comment]
Hi @trampi,

i actually found the reason, which someone might actually benefit from in the future: dont activate "archive group chats" for the monitoring service plugin on openfire, that actually saves groupchats as 1 v 1 chats! 

best regards
DevRichter

**Comment by trampi** [comment]
Hi @DevRichter,

thanks for the heads up.

All the best,
trampi
