### ISSUE TITLE
Writing Jasmine/Karma tests involving ngxchat

### ISSUE THREAD

**Issue by DevRichter** [pazznetwork/ngx-chat#51]
Hey,

i have a question regarding how to write tests using this repository. I have to use the Jasmine/Karma testing framework from Angular. I am not very well versed in writing tests, but as far as i understand you normally would mock incoming data, and tests the functions with the mocked data. In that way you would need to mock the objects with all of their attributes, for it to work. Using this repository though, the datastructers have very many attributes, and mocking those seems like a daunting task, for someone inexpirienced. Is there any advise for testing? 

Best regards
DevRichter

**Comment by trampi** [comment]
Hi @DevRichter,

in our main project, we just use end-to-end-tests with ngx-chat. We have no unit tests / component tests involving ngx-chat, as we see that as "external library" and try to avoid testing external libraries, because that should be the burden of the external library developer.
In your use case, I would recommend to mock the data regarding ngx-chat. It might be possible, depending on what exactly you're testing, to just override some attributes, in particular read about [spyOn](https://jasmine.github.io/api/edge/global.html#spyOn) in jasmine.
Maybe a barebone mock implementation of `ChatService` is sufficient?

All the best,
trampi

PS: I am currently on paternal leave and will be back in office in march, until then I my replies might be delayed.

**Comment by DevRichter** [comment]
Hey @trampi,

thanks for the answer and congratulations for becoming a father! I think mocking ChatService should be sufficient, you're right. I tried mocking my wrapping Service, which of course wont work, thanks for the advice! 

Greetings
DevRichter
